// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5VmHOq5LnaefbNyLRVjyRWMyAwLVCAH8',
    appId: '1:280523253606:web:b8a953c7538e4bec320aa7',
    messagingSenderId: '280523253606',
    projectId: 'chat-app-42f69',
    authDomain: 'chat-app-42f69.firebaseapp.com',
    storageBucket: 'chat-app-42f69.appspot.com',
    measurementId: 'G-NVY75FXS7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5-ylD666kxMgl_c9kIr5__wYfmi-LSM',
    appId: '1:280523253606:android:187f4cf0636c4d51320aa7',
    messagingSenderId: '280523253606',
    projectId: 'chat-app-42f69',
    storageBucket: 'chat-app-42f69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjCgcskaZI6NZjOkIM-hNPnAu51duO4WA',
    appId: '1:280523253606:ios:4d87957eb9d8d4f4320aa7',
    messagingSenderId: '280523253606',
    projectId: 'chat-app-42f69',
    storageBucket: 'chat-app-42f69.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjCgcskaZI6NZjOkIM-hNPnAu51duO4WA',
    appId: '1:280523253606:ios:4d87957eb9d8d4f4320aa7',
    messagingSenderId: '280523253606',
    projectId: 'chat-app-42f69',
    storageBucket: 'chat-app-42f69.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5VmHOq5LnaefbNyLRVjyRWMyAwLVCAH8',
    appId: '1:280523253606:web:382697e4d7ee14f0320aa7',
    messagingSenderId: '280523253606',
    projectId: 'chat-app-42f69',
    authDomain: 'chat-app-42f69.firebaseapp.com',
    storageBucket: 'chat-app-42f69.appspot.com',
    measurementId: 'G-7T3BMV57LM',
  );
}
